### ISSUE TITLE
Fix potential NPE in param stripping method

### ISSUE THREAD

**Issue by shortstuffsushi** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#103]
Per the BranchMetrics/Branch-Unity-SDK#3 PR, we need to make sure we're covering the case for null Activities getting into [this method](https://github.com/BranchMetrics/Branch-Android-SDK/blob/f23f48a2c62a36d5654e9d390d35230da50788e8/Branch-SDK/src/io/branch/referral/Branch.java#L1039-L1059).

**Comment by sojanpr** [comment]
Fixed with release  1.8.0
