### ISSUE TITLE
Share sheet is not internationalized 

### ISSUE THREAD

**Issue by jbkielis** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#120]
"Copy link" and "More" are hardcoded which makes it impossible to internationalize them.

Would be great to support dynamic names for those items so they can be internationalized.

Thanks.

**Comment by sojanpr** [comment]
@jbkielis  Thanks for reaching out. We have updated sdks with v1.8.7 with internationalization option for the share link dialog. We have added the following option to the builder to enable internationalization option. 
`setMoreOptionStyle(Drawable icon, String label)`
`setCopyUrlStyle(Drawable icon, String label, String message)`

Could you please update to v1.8.7 and try again.

Thank you very much

**Comment by sojanpr** [comment]
@jbkielis  Does this helpmate solve the issue. Could you please  let us know if you need any thing form our SDK?

Thanks

**Comment by SleeplessByte** [comment]
It would be great if those options also accept a `@StringRes int stringResource`, so i18n can be done through resource-directories.

**Comment by sojanpr** [comment]
Added the changes for supporting res ids for strong and drawables passed to the share link builder
https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/pull/124

**Comment by SleeplessByte** [comment]
:+1:
