### ISSUE TITLE
Short URL conflicts lead to repeated requests

### ISSUE THREAD

**Issue by spennington** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#130]
If a conflict occurs while using `BranchShortLinkBuilder.generateShortUrl()` the request will never be removed from the queue. Looking at `BranchPostTask.onPoseExecute()` it seems that requests are not removed from the queue when the `statusCode` is `409`. This means that any time the request queue is nudged the same request will be retried.

https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/blob/6b4358e11c8adbe3d25d7b72919ce80647675612/Branch-SDK/src/io/branch/referral/Branch.java#L2883

**Comment by sojanpr** [comment]
@spennington  Thank you very much for pointing this out. We have created  a pull request for this issue (https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/pull/131) .Do you think fix will solve the issue?

**Comment by spennington** [comment]
Looks like it will fix the issue. I added one comment on the PR about when the request is dequeued.

**Comment by sojanpr** [comment]
Fixed with SDK v1.8.9
