### ISSUE TITLE
Generate Url on server side

### ISSUE THREAD

**Issue by ArsalRaza** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#170]
Hi Guys...!
  I am implementing branch io in an application. My question is that can I generate short url from the server side? I didn't find any documentation about this...!
  I am trying to generate a url only when the item is saving on the server, in this way I don't need to generate a new url from branch io every time...!
Please update me for the implementation of the branch io on server-hand.

**Comment by dmitrig01** [comment]
Hi Arsal,
Sorry about the delay in reply here. In the future, if you email support@branch.io, you'll get a much faster response.
You most certainly can create links from the server side. Please see https://dev.branch.io/references/http_api/#creating-a-deep-linking-url for details.
