### ISSUE TITLE
android has no campaign attribute for LinkProperties ?

### ISSUE THREAD

**Issue by pcompassion** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#185]
iOS has it and Android doesn't it seems.

**Comment by derrickstaten** [comment]
@pcompassion actually we do not offer this on iOS. `campaign` is a parameter that may be retrieved in-app, but it's only really intended to be set on Marketing links. We provide other ways of labeling links so you can see aggregate analytics, the most versatile being `tags`.

We're closing this for now. Please let us know if you have other questions about this, including other alternatives to `campaign`.
