### ISSUE TITLE
getFirstReferringParams always empty..

### ISSUE THREAD

**Issue by pcompassion** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#186]
branch doc for android is confusing.

Here's my setup and I can't figure out why clicking the link I created won't seem to do no good. ie. getFirstReferringParams return empty.

manifest
```
     <meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_hkbLTX5FhhLkWx=====" />
     <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_dkcNL46yckHbYFkCABN====" />
```

MyApplication.java

     @Override
     public void onCreate() {
         super.onCreate();

         // branch.io
         // https://dev.branch.io/recipes/quickstart_guide/android/#alternatives-to-application-subclass
         Branch.getAutoInstance(this);
     }

Then I create a link to share like the following..

     public void createInvitationUrl(String invitation_id, final Handler.Callback callback) {
         BranchUniversalObject branchUniversalObject = new BranchUniversalObject()
             .setCanonicalIdentifier(EVENT_NAME)
             .addContentMetadata(INVITATION_ID_PARAM_NAME, invitation_id);

         LinkProperties linkProperties = new LinkProperties()
             .setFeature("sharing");

         Context context = LittleHomeApplication.getContext();

         branchUniversalObject.generateShortUrl(context, linkProperties, new Branch.BranchLinkCreateListener() {
             @Override
             public void onLinkCreate(String url, BranchError error) {
                 if (error == null) {
                     Log.i("MyApp", "got my Branch link to share: " + url);

                     Message message = new Message();
                     message.obj = url;
                     callback.handleMessage(message);
                 }

             }
         });
     }

Now my app is published to the playstore and when I click the link and install the app via playstore.

I see `      JSONObject installParams = branch.getFirstReferringParams();` is empty..

why? I can't figure this out for a whole day..

**Comment by sojanpr** [comment]
@pcompassion Thanks for reaching out and sorry to see you have issues with gettingFirstReferrerParams(). The  first referring params get set when you open the app for the first time. The  only option to skip it is if you specify "referrable = false". 
Normally this option is set with getAutoInstance() call.Could you please make sure you are NOT calling `Branch.getAutoInstance(context, false)`

**Comment by pcompassion** [comment]
I changed to Branch.getAutoInstance(context, true) from Branch.getAutoInstance(context) . but still no go.


I think the problem is on the making the link.

In my test,
```
iOS -> iOS works fine
iOS -> android works fine

android -> iOS first param empty
android -> android first param empty
```

So I guess getFirstReferringParams is not an issue, it's the link that android created doesn't work for a reason.

Do you have any suggestions?

**Comment by pcompassion** [comment]
I changed something here and something there. It works now but not sure what was the cause.

Main changes are
    Branch.getAutoInstance(this) -> Branch.getAutoInstance(this, true)
    Branch.getInstance(context) -> Branch.getInstance() 
    Do not call initSession when you have getAutoInstance()

**Comment by SArshpreetAI** [comment]
Do we get the params only when a branch link was used to install the app? Or is it general. 

Also can you tell me if I can test this process by downloading my app from google play store by using the link `link-to-app?&utm=test_branch_param`. Will I get the 
```
utm: test_branch_param
```

in the data?
