### ISSUE TITLE
What's the meaning of isReferrable in getAutoInstance() ?

### ISSUE THREAD

**Issue by pcompassion** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#187]
what is the meaning of `isReferrable` ?

Does it mean, `Can be regarded as a fresh install`?

**Comment by sojanpr** [comment]
@pcompassion `isReferrable` indicates whether or not the current session should be considered referrable. This is to avoid invalid install count while you do testing and debugging with your app.
Please let us know if you still have issues with it

**Comment by pcompassion** [comment]
My english isn't that good I guess, 

A current session should be considered referrable: Does it mean any of the following two?

We can consider this session as a session that is referred (link-clicked). 
We can consider this session can refer (give a link) a user to something

**Comment by sojanpr** [comment]
@pcompassion `isReferrable` means the We can consider this session as a session that is referred (link-clicked).
