### ISSUE TITLE
Update styling of share dialog

### ISSUE THREAD

**Issue by aashrairavooru** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#190]
The share dialog provided by branch is super convenient but it's hasn't kept up with the material design principles

**Comment by sojanpr** [comment]
@aashrairavooru  Thank you very much for trying the Branch Share sheet. Your suggestion is really valid. We will definitely add more styling option and material  theme in the next  update.

**Comment by sojanpr** [comment]
Share dialog is basically a  list with n elements. SDK v 1.10.3 provides more options to (`setShareSheetStyle( int styleResId)`) to define style for share sheet
