### ISSUE TITLE
Store error code in BranchError class

### ISSUE THREAD

**Issue by aashrairavooru** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#191]
Storing the error code will help in taking a custom action for a set of error codes, like problems with network etc

**Comment by sojanpr** [comment]
@aashrairavooru  Thank you for bringing this to our attention. Your suggestion is very valid and  we will definitely add `int getErrorCode()` method in `BranchError` class with next sdks upgrade

**Comment by aashrairavooru** [comment]
Okay cool will put a PR for this then

**Comment by sojanpr** [comment]
@aashrairavooru I have already created a PR for this issue https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/pull/192. Do you think this is enough to support the  error codes

**Comment by aashrairavooru** [comment]
Awesome that you guys are so responsive, when are you planning to do the
next release?

**Comment by sojanpr** [comment]
@aashrairavooru our next planned release on 5th January.

**Comment by sojanpr** [comment]
This issue is fixed with release 1.10.3
