### ISSUE TITLE
onInitFinished referringParams not cleared

### ISSUE THREAD

**Issue by RafalManka** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#202]
after onInitFinished(JSONObject referringParams, BranchError error)

i get the params I want from referringParams and that works perfectly, but then when I go to a different app and back, the call to method onInitFinished still is triggered with the same params as previously.

I noticed then when I call Branch.getInstance().resetUserSession(); from inside the onInitFinished callback, the call is not repeated, but is that the correct way?

**Comment by sojanpr** [comment]
@RafalManka  Thanks for reaching out. We have fixed this issue a long time back .Could you please make sure you are using the latest SDK .Latest version is 1.10.4
  Also could you please make sure you have the following for your main activity
1.Launch mode set to single Task (android:launchMode="singleTask" in manifest for main activity)
2.Make sure to set new  intent in main activity
    ```@Override
    public void onNewIntent(Intent intent) {
        this.setIntent(intent);
    }```

**Comment by sojanpr** [comment]
@RafalManka  Hope the above comments helped to solve the issue. In order to get a faster response, could you please email your implementation questions to support@branch.io?
