### ISSUE TITLE
1.10.5 breaking builds

### ISSUE THREAD

**Issue by elincoln** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#207]
I don't see a tag for it 1.10.5, but its on jcenter, being vended out to gradle configs using `compile 'io.branch.sdk.android:library:1.+'` and is also up on your AWS direct download.

Build-break being caused by this PR #204

**Comment by Sarkar** [comment]
Hey @elincoln - thanks for opening this. Can you specify what's breaking? Do you have any code relying on these private methods? Let us know

**Comment by elincoln** [comment]
It was all related to the debug mode, i couldn't get it reliably working using your touch hijacking code, so i disabled it and wrote a toggle for my SettingsActivity.  It looks like that live-debug-mode thing is completely removed now from both web and SDK?  

If that's the case I can just delete my code. It's not production related in any way, I just wasn't expecting a build break out of a patch release.  `PrefHelper` is meant to be private?

**Comment by Sarkar** [comment]
@elincoln - nice - this was the intended reason for removing the touch-hijacker; it ended up causing more pain than solving. You are correct, we have removed this from our SDK.

we plan on making `PrefHelper` package private now (hopefully as soon a next release), as removing this allows us to do that. But yes, it's intended to be private. Sorry about this. I'll leave this open for a little while until we move on to the next release.

**Comment by elincoln** [comment]
@Sarkar Sounds good to me; thanks for the quick responses! :smile:
