### ISSUE TITLE
java.util.ConcurrentModificationException in ServerRequestQueue

### ISSUE THREAD

**Issue by akki-123** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#211]
using branch  'io.branch.sdk.android:library:1.10.2' 
is this the same issue as [this one](https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/issues/198)
`java.util.HashMap$HashIterator.nextEntry (HashMap.java:806)
org.json.JSONArray.toString (JSONArray.java:574)
io.branch.referral.ServerRequestQueue$1.run (ServerRequestQueue.java:81)
java.lang.Thread.run (Thread.java:841)`

<img width="975" alt="screen shot 2016-02-17 at 1 01 41 pm" src="https://cloud.githubusercontent.com/assets/8477541/13102931/ec5f9404-d577-11e5-9089-1b7beeb8ebfb.png">

**Comment by sojanpr** [comment]
@akki-123 Thanks for reaching out and sorry for the issue. It is caused by a  bug in 1.10.2. It is fixed from 1.10.4. Issue is caused by the same reason as https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/issues/198
