### ISSUE TITLE
I am Using BranchIO for my project , I am sending Title and image in the branch Universal object which can be show in the message send via whatsapp, but since the whatsapp has been upgraded the title and image is not been show , as it was earlier.Please help me ,What is the problem?

### ISSUE THREAD

**Issue by shrutika229** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#213]
BranchUniversalObject branchUniversalObject = new BranchUniversalObject()
                // The identifier is what Branch will use to de-dupe the content across many different Universal Objects
                .setCanonicalIdentifier("item/12345")
                // This is where you define the open graph structure and how the object will appear on Facebook or in a deepview
                .setTitle("Suits")
                .setContentDescription("Great suits here")
                .setContentImageUrl("http://steezo.com/wp-content/uploads/2012/12/man-in-suit.jpg")
                // You use this to specify whether this content can be discovered publicly - default is public
                .setContentIndexingMode(BranchUniversalObject.CONTENT_INDEX_MODE.PUBLIC)
                // Here is where you can add custom keys/values to the deep link data
                .addContentMetadata("picurl", "http://steezo.com/wp-content/uploads/2012/12/man-in-suit.jpg");

THis Title and ContentImageUrl is not working

**Comment by sojanpr** [comment]
@shrutika229 Thanks for reaching out. Since this is an implementation question and not an SDK issue you can better help from our awesome support team. In order to get a faster response, could you please email your implementation questions to support@branch.io?
