### ISSUE TITLE
Callback listener for userCompletedAction

### ISSUE THREAD

**Issue by renesansz** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#226]
In regards to this [issue](https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/80) reported.
"userCompletedAction still needs a way to resolve a promise depending on if the http call succeeded / via a listener; it returns too early right now"

He suggested that in order to resolve the issue, it should also have a callback listener implemented.

**Comment by qandeelabbassi** [comment]
is this listener available yet?
