### ISSUE TITLE
Android - Deep linking not working in chrome

### ISSUE THREAD

**Issue by v-pandiarajan-swaas** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#237]
Hi,
I have integrated the branch.io SDK with my android app. I created the deep link URL with custom URI scheme(drbond://) in the dashboard.  When clicking the deep link from a mobile browser it takes me to the app(If installed). But in chrome, it doesn't. I tried with Opera, Mozilla, and other default browsers are working fine.  Please help me to deep linking working in chrome. 

FYI,
My activity intent filter,

```
<intent-filter>
               <data android:scheme="drbond"  android:host="open" />
               <action android:name="android.intent.action.VIEW" />
               <category android:name="android.intent.category.DEFAULT" />
               <category android:name="android.intent.category.BROWSABLE" />
</intent-filter>
```

**Comment by EvangelosG** [comment]
Hi there, I noticed you wrote into support about this and I have replied. Let's continue the conversation there.

**Comment by EvangelosG** [comment]
Resolved directly over support.

**Comment by v-pandiarajan-swaas** [comment]
Thanks, EvangelosG.

**Comment by waqqas-imena** [comment]
Wouldn't it make sense to provide a link to the support ticket so that others with the same issue can benefit as well?

**Comment by EvangelosG** [comment]
Hi Waqqas, the above issue was due to an incorrect package name being used in the Branch Dashboard's link settings page.

**Comment by chabislav** [comment]
@EvangelosG What do you mean by incorrect package mane in the Branch Dashboard? I don't understand where the package name should go there... Could you explain. Thanks

**Comment by EvangelosG** [comment]
Hey @chabislav -- go to https://dashboard.branch.io/settings/link -> scroll down to your Android App settings and instead of "Google Play Search" select "Custom URL" and you'll be able to set your app's package name manually, it's great for non-release build testing when you may have multiple build flavors. If you have additional questions and would like 1:1 attention, please write to integrations@branch.io and I can help out 👍

**Comment by chabislav** [comment]
Got it! Thanks for a quick response!

**Comment by miankhalid** [comment]
This should be mentioned somewhere in the official integration doc, I spent a whole day figuring out what I was doing wrong 😢

**Comment by EvangelosG** [comment]
Hey @miankhalid -- Sorry for the headache! We are currently revamping our entire docs portal, custom URL is mentioned in our new flow. I will review it to make sure things are clear and if not I'll submit a PR. Thanks for letting me know, we want this process to be as easy to understand/implement as possible.

**Comment by LukasStancikas** [comment]
Hello, the problem still exists, we have custom url + correct package name setup, link domain exists etc. The app link works when opening from firefox, gmail, slack nd messenger, but insering the link to chrome it opens google play store, when trying to open from skype app it goes through even weirder behavior: for some time it shows a button (inside the skype browser) to go to the app, then automatically goes to playstore and the automatically goes to the app

**Comment by sojanpr** [comment]
@LukasStancikas is it possible to share a link which causes this issue? It would help debugging a lot. It looks like a config issue with chrome intents. Additionally always feel free to write to integration@branch.io for quick responses on these kind of issues

**Comment by LukasStancikas** [comment]
@sojanpr yes here it is https://menucard.app.link/vCmG6eintN. The app is in playstore but not the version with deeplink yet as it does not pass the testing phase

**Comment by sojanpr** [comment]
@LukasStancikas A quick test with chrome seems opening the app fine. Some version of chrome had issue when you copy and paste the link in the address bar. Are you testing by pasting link in the address bar?
Additionally noticed that the manifest for app has no intent filter added for `menucard.app.link`

**Comment by LukasMediapark** [comment]
@sojanpr Yes i'm pasting the link in chrome, how did you open it, were you just clicking on the link in chrome window? the app in play store as i mentioned is not updated with latest changes regarding branch.io, in the latest version from my PC build i have the intent filter added

**Comment by sojanpr** [comment]
@LukasMediapark I opened it both by 
1) pasting the link in chrome and 2) clicking a link shared (which eventually opens chrome and then the application)  
Can we move this to the our awesome integration support team for more debugging with the app and config. Can you please write to integrations@branch.io

**Comment by LukasStancikas** [comment]
@sojanpr which android version and what device were you using, i seem to replicate the same problem (going to playstore and staying there) on both Sony Xperia XZ, Samsung S8 (both with android 8.0) and even emulator running android 8.1 with play store and play services

**Comment by sojanpr** [comment]
@LukasStancikas I used s8 with 8.0. Here are the steps I followed after installing app
1. Copy the link and paste it in Chrome (shows PS  even if app is installed)
2. Click the link from some messaging app (open link in chrome and then opens the app)
3. Repeat step1 (Always open the app)
It always open the app through chrome if the link is clicked and opened instead of pasting in navigation bar

**Comment by VvoidVano** [comment]
any solutions ?

**Comment by WarunaS** [comment]
Any Solution for this?

**Comment by rituapplocum** [comment]
Branch io not working from Opera browser.Do I have to make any changes in Manifest or Branch Dashboard, It is working fine in Firefox,Chrome,Gmail

**Comment by jf-branch** [comment]
Hi @rituapplocum If its working on other browsers, your manifest and Branch Dashboard are most likely fine. Could you provide the link in question? As well as the UX you are experiencing so I can pass this over to our Linking Team who can look into this further.

**Comment by AasthaDoshi-optimus-avdevs** [comment]
Hi, I'm facing similar issue. I've added correct package name too. Can anyone assist on this?

**Comment by AasthaDoshi-optimus-avdevs** [comment]
Hi @EvangelosG @sojanpr, 
I already wrote my queries in integrations@branch.io but still no revert from their side. My app link is https://nrnvs.test-app.link/TpQHWCLRtOb Can you please assist me what's wrong here? When I copy paste URL in chrome browser it opens play store even of the app is installed.

**Comment by sojanpr** [comment]
@AasthaDoshi-optimus-avdevs Could you please double check your manifest and Branch dashboard to ensure the package name and deep link scheme is correct. (Unfortunately I can't see it. I am not with Branch anymore).
 Do you see the app getting opened if you click open the link (rather than pasting the link)?

**Comment by AasthaDoshi-optimus-avdevs** [comment]
> @AasthaDoshi-optimus-avdevs Could you please double check your manifest and Branch dashboard to ensure the package name and deep link scheme is correct. (Unfortunately I can't see it. I am not with Branch anymore). Do you see the app getting opened if you click open the link (rather than pasting the link)?

Hi @sojanpr, Thank you for your reply!

Yes app gets open when I click on the link but when I copy paste it on chrome browser play store gets open.
Inside Branch Dashboard Android URI scheme is : https://api-dev.klara-epost.tech/branch-qr:// where :// is automatically appended at the end and in my manifest it is like the following:

<activity
            android:name=".activities.SplashScreen"
            android:exported="true"
            android:launchMode="singleTask"
            android:screenOrientation="portrait">

            
            <intent-filter>
             <data android:scheme="https" />
                <data android:host="api-dev.klara-epost.tech" />
                     <data android:pathPrefix="/branch-qr"/>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>

            
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https"/>
                <data android:host="${TEST_APP_LINK_VALUE}"/>
            </intent-filter>

            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="https"/>
                 <data android:host="${ALTERNATE_TEST_APP_LINK_VALUE}"/>
            </intent-filter>
            ----

**Comment by shuo-hiwintech** [comment]
I have the same problem. Everything works fine when opening deep links in other browsers, but when copied to Google Chrome, the app store opens.

"react-native": "0.79.5",
"react-native-branch": "^6.8.0",
