### ISSUE TITLE
How can I open get parameters from branch link without opening it like deep-link?

### ISSUE THREAD

**Issue by ray1984** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#241]
I need to get parameters from branch link without application restart. It is uncomfortable for user when I open branch link as
```
startActivity(new Intent(Intent.ACTION_VIEW).setData(Uri.parse(link)));
```
and in first time user should choose an application, where he want open that link

**Comment by aaustin** [comment]
Hey Ray - we never added a function to the SDK to do this it didn't occur to us as a use case. However, you can use this API endpoint we have to retrieve the parameters: https://github.com/BranchMetrics/Deferred-Deep-Linking-Public-API#viewing-state-of-existing-deep-linking-urls

Hope this helps!

**Comment by sclancy** [comment]
> we never added a function to the SDK to do this it didn't occur to us as a use case.

That's a shame. It would be very useful. I want to embed a link in a QRCode, so during on boarding a user could scan the code, I can would extract the parameters so I can customise on boarding without leaving the app. 

Without this feature I need to open the url and the user now exits the app :(

**Comment by sojanpr** [comment]
@sclancy we added support for this use case recently. SDK provides option to add a link to an activity and get params. Please check here
https://github.com/BranchMetrics/android-branch-deep-linking#deeplink-via-push-notification

Once you get the link from QR code activity launch your activity to receive the deep link params with above inent.

**Comment by mlostekk** [comment]
This documentation is quite bad. Do you have any further information about how to parse a link and get the BranchUniversalObject without restarting the activity? Just think of the usecase of a QRcode and scanned within the application.

Is there really no functionality to simply parse an Uri and get the information? (`public boolean initSession(BranchUniversalReferralInitListener callback, @NonNull Uri data)` does not work)

**Comment by sojanpr** [comment]
@mlostekk Really sorry that you are having an issue with the documentation. The link shared in the above comment is specifically for handling deep linking through push notifications. For the QR code can you please try the following
1.  `QR code scanner Activity`  scans the QR code and get the Branch link embedded  in the QR Code
2. Open your`DeepLinkActivity.java` with the following intent
      ```
        Intent intent = new Intent(ScannerActivity.this, DeepLinkActivity.class);
        intent.putExtra("branch_force_new_session", true);
        intent.putExtra("branch", "branch_link_embedded_in_qr_code");
        ScannerActivity.this.startActivity(intent); 
```
3. In your DeepLlinkActivity.java#onStart()
```
Branch.getInstance().initSession(new Branch.BranchUniversalReferralInitListener() {
            @Override
            public void onInitFinished(BranchUniversalObject branchUniversalObject, LinkProperties      linkProperties, BranchError error) {
                // Use the BUO 
            }
        })
```
Unfortunately SDK doesn't support init again in the same activity. If you are looking for getting the deep link params without using intent as explained above please try our public API to retrieve link params
https://github.com/BranchMetrics/branch-deep-linking-public-api#viewing-state-of-existing-deep-linking-urls

**Comment by mlostekk** [comment]
Well, this is not possible in my setup. I cant start the DeepLinkAcitivty from my ScannerActivity due to dependency restrictions.

I am starting the `ScannerActivity` with `startActivityForResult` and returning the qr code to the `ScannerActivity` with `setResult` and `finish`. In this situation your mentioned solution does not work (`onInitFinished` is invoked with null objects).

Is there a way for my setup to solve this without restarting the whole application?

**Comment by sojanpr** [comment]
@mlostekk  Thanks for explaining the way you need it. You can achieve this simply by doing the following
```
 protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == SCANNER_ACTIVITY_LAUNCH_CODE) {
            // Get link from scanner activity here
            getIntent().putExtra("branch_force_new_session", true);
            getIntent().putExtra("branch", "branch_link_embedded_in_qr_code");
        }
    }
```
Now you will get the deep link params in  `InitFinished()` . Please make sure you reset the both params added to the intent params after receiving the params.

**Comment by sojanpr** [comment]
@mlostekk Hope the above helped to solved the issue?

**Comment by mlostekk** [comment]
Hello @sojanpr 

unfortuantely initSession still returns with all objects = null

**Comment by mlostekk** [comment]
by the way.. should `getIntent().putExtra("branch", "branch_link_embedded_in_qr_code"); ` contain a string or an uri?

**Comment by mlostekk** [comment]
Okay, it seems to be working with an `Uri`. I will do intense testing and get back with the results. Thanks for your help

**Comment by sojanpr** [comment]
@mlostekk Glad that you got it working.  Let us know if you find any other issue
