### ISSUE TITLE
Public API revisitation

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#83]
With eye on #76, this would probably a great time to clean-up the public API exposed by the library.

The files
- ApkParser
- BranchLinkData
- BranchRemoteInterface
- RemoteInterface
- ServerRequest
- ServerRequestQueue
- ServerResponse
- SystemObserver

should be package-local and not public. They are not supported in terms of "outside-branch" use and might undergo heavy modification and thus should not be publicly exposed. 

Simply remove the word public in front of the class. Since are all in the same package, it won't change anything internally. Bonus: since they are not public any more, Proguard can do way better job.

**Comment by sojanpr** [comment]
Closing issue since the only necessary classes are exposed now. All others are  changed to package local
