### ISSUE TITLE
Consider moving towards Java 7 or even 8

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#84]
As an example: https://github.com/SleeplessByte/Branch-Android-SDK/tree/feature/consider-java-7

Since Android now supports Java 7 out of the box, you should consider building for it. Java 8 is coming, but it's best feature, lambda's, can already be used using https://github.com/evant/gradle-retrolambda. 

Especially because you have a lot of runnables, this might be worth looking into.
https://www.youtube.com/watch?v=DUdhfPh9V_s

**Comment by shortstuffsushi** [comment]
While I agree this would be great, we have to continue compiling for 6 because of other SDKs (specifically the [Unity SDK](https://github.com/BranchMetrics/Branch-Unity-SDK) requires 6).

**Comment by shortstuffsushi** [comment]
For reference, [this is where](http://docs.unity3d.com/Manual/PluginsForAndroid.html) that requirement comes from.

**Comment by SleeplessByte** [comment]
Ah, that's unfortunate and it's going to be a problem, as the preview releases of Android already dropped support for Java 6, and anyone targeting 21+ **must** use Java 1.7+. 

````
Error:compileSdkVersion android-21 requires compiling with JDK 7
````

**Comment by SleeplessByte** [comment]
Added note: yes, source compat. can still be kept at 1.6, but that will be dropped in the future. This is more a note for the Unity team then you guys :+1:

**Comment by sojanpr** [comment]
@SleeplessByte  we have updated  the sdks compilation o 1.7+ some time back and we have updated the code also to comply with the latest format. Do you think we can close this issue with these changes

**Comment by SleeplessByte** [comment]
Fine with me :+1:
